# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='task_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Task'),
        ),
        migrations.AlterField(
            model_name='process',
            name='task_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Task'),
        ),
    ]
