# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinstance',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.TaskInstance'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='status',
            field=models.CharField(choices=[('student_pending', 'Student Pending'), ('staff_pending', 'Staff Pending'), ('fail', 'Fail'), ('success', 'Success')], default='student_pending', max_length=20),
        ),
    ]
