# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180210_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='next_task_success',
            new_name='next_task_accept',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='next_task_fail',
            new_name='next_task_reject',
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='status',
            field=models.CharField(choices=[('student_pending', 'Student Pending'), ('staff_pending', 'Staff Pending'), ('reject', 'Reject'), ('accept', 'Accept')], default='student_pending', max_length=20),
        ),
    ]
