# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180210_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='task_end',
        ),
        migrations.AddField(
            model_name='task',
            name='end_task',
            field=models.BooleanField(default=False),
        ),
    ]
