# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
