# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_task_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(default='Mellat', max_length=100)),
                ('card_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payer', models.CharField(blank=True, max_length=100)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Payment'),
        ),
    ]
