# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180214_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='processinstance',
            unique_together=set([('student', 'process')]),
        ),
        migrations.AlterUniqueTogether(
            name='taskinstance',
            unique_together=set([('process_instance', 'task')]),
        ),
    ]
